# Generated by Django 3.1.7 on 2021-03-27 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ToiletPaper',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('in_stock', models.IntegerField(default=0)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('composition', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
